services:
  - type: web
    name: resume-screening-agent
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run Home.py --server.port=10000 --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
