services:
  - type: web
    name: resume-screening-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run Home.py --server.port=$PORT --server.address=0.0.0.0"
    plan: free
